# This file was generated by https://github.com/kamilchm/go2nix v2.0-dev
{ pkgs, stdenv, buildGoPackage, fetchFromGitHub, ... }:
with import <nixpkgs> {};

buildGoPackage rec {
  name = "go2nix-unstable-${version}";
  version = "0.2-dev";

  goPackagePath = "github.com/kamilchm/go2nix";
  subPackages = [ "cmd/go2nix" ];

  src = fetchFromGitHub {
    owner = "kamilchm";
    repo = "go2nix";
    rev = "6cd52450c74f013a7e7c284526b3983dd918b070";
    sha256 = "1bazkn7f5pydcqsvqg8yfx56h4162i2sya8q835ssc8bbp5y8as6";
  };

  goDeps = ./go2nix-deps.nix;

  meta = {
    homepage = "https://github.com/kamilchm/go2nix";
    description = "Reproducible builds and development environment for Go";
  };
}
