# This file was generated by go2nix.
[
  {
    goPackagePath = "github.com/Masterminds/vcs";
    fetch = {
      type = "git";
      url = "https://github.com/Masterminds/vcs";
      rev = "fbe9fb6ad5b5f35b3e82a7c21123cfc526cbf895";
      sha256 = "09rdq8k2smwgy6wdslddcq13wg3lzd4amzpy0f8kd0hlxxvas89c";
    };
  }
  {
    goPackagePath = "github.com/jawher/mow.cli";
    fetch = {
      type = "git";
      url = "https://github.com/jawher/mow.cli";
      rev = "772320464101e904cd51198160eb4d489be9cc49";
      sha256 = "1a8hnh2k3vc3prjhnz4rjbiwhqq6r3mi18h9cdb6fc6s6yzjc19j";
    };
  }
]
