# This file was generated by https://github.com/kamilchm/go2nix v2.0-dev
[
  {
    goPackagePath = "github.com/Masterminds/semver";
    fetch = {
      type = "git";
      url = "https://github.com/Masterminds/semver";
      rev = "517734cc7d6470c0d07130e40fd40bdeb9bcd3fd";
      sha256 = "1625b5sxpmlz60jw67j1ljfcc09d4lhxg3z6gc4am8s2rrdgwij6";
    };
  }
  {
    goPackagePath = "github.com/Masterminds/vcs";
    fetch = {
      type = "git";
      url = "https://github.com/Masterminds/vcs";
      rev = "3084677c2c188840777bff30054f2b553729d329";
      sha256 = "1062m73h0pp5d0574lf6px4jsjgywnsbkw50inxx3zal5r185ydm";
    };
  }
  {
    goPackagePath = "github.com/pelletier/go-buffruneio";
    fetch = {
      type = "git";
      url = "https://github.com/pelletier/go-buffruneio";
      rev = "c37440a7cf42ac63b919c752ca73a85067e05992";
      sha256 = "0l83p1gg6g5mmhmxjisrhfimhbm71lwn1r2w7d6siwwqm9q08sd2";
    };
  }
  {
    goPackagePath = "github.com/pelletier/go-toml";
    fetch = {
      type = "git";
      url = "https://github.com/pelletier/go-toml";
      rev = "5ccdfb18c776b740aecaf085c4d9a2779199c279";
      sha256 = "1jl44j58y62rhnwkzw3mvcj725gdyzs45pq4ga81qqxwqxs3czsq";
    };
  }
  {
    goPackagePath = "golang.org/x/tools";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/tools";
      rev = "e6cb469339aef5b7be0c89de730d5f3cc8e47e50";
      sha256 = "16q3ibisbzq8rx4irhzl2lw4nwr62x9ryv446kgic8ww3p30rlf9";
    };
  }
]
